/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import CRUD.crudgrafikanggota;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class grafik_anggota extends javax.swing.JPanel {
 crudgrafikanggota ob=new crudgrafikanggota();
 

 public grafik_anggota() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setText("Pilih Grafik Yang ditampilkan");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_cancel_48px.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButton1.setText("Grafik Pendaftaran Anggota");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(168, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(248, 248, 248)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String inputantahun = JOptionPane.showInputDialog("Masukan Grafik Tahun Berapa ");
        
        DefaultCategoryDataset obj=new DefaultCategoryDataset();
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-01-01", ""+inputantahun+"-01-31"),"Januari", "Januari");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-02-01", ""+inputantahun+"-02-31"),"Februari", "Februari");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-03-01", ""+inputantahun+"-03-31"),"Maret", "Maret");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-04-01", ""+inputantahun+"-04-31"),"April", "April");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-05-01", ""+inputantahun+"-05-31"),"Mei", "Mei");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-06-01", ""+inputantahun+"-06-31"),"Juni", "Juni");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-07-01", ""+inputantahun+"-07-31"),"July", "July");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-08-01", ""+inputantahun+"-08-31"),"Agustus", "Agustus");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-09-01", ""+inputantahun+"-09-31"),"September", "September");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-10-01", ""+inputantahun+"-10-31"),"Oktober", "Oktober");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-11-01", ""+inputantahun+"-11-31"),"November", "November");
        obj.setValue(ob.cetakperbulan(""+inputantahun+"-12-01", ""+inputantahun+"-12-31"),"Desember", "Desember");
        
        JFreeChart chart=ChartFactory.createBarChart3D("Grafik Pendaftaran Anggota Bank Sekolah Per Bulannya Tahun "+inputantahun+"", "Bulan Pendaftaran","Jumlah Anggota Per Bulannya",obj);
        CategoryPlot objplot=chart.getCategoryPlot();
        objplot.setRangeGridlinePaint(Color.black);
        ChartFrame frame=new ChartFrame("Grafik Pendaftaran Nasabah",chart);
        frame.setExtendedState(ChartFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
